name: 💡 Feature Request
description: Suggest an idea for Flowform
title: "[Feature]: "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

        Before submitting, please check:
        - [ ] This feature isn't already in [TASKS_MVP.md](https://github.com/kayossouza/flowform/blob/main/docs/TASKS_MVP.md)
        - [ ] This hasn't been suggested in [Discussions](https://github.com/kayossouza/flowform/discussions)

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you solve this problem?
      placeholder: I think we could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: I also thought about...

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: When do you think this feature should be implemented?
      options:
        - v1.0 (MVP)
        - v1.1 (Post-MVP)
        - v2.0 (Future)
        - Not sure
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      options:
        - label: I'm willing to implement this feature
        - label: I'm willing to help test this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples here
